:construction_worker: validate pub.dev topics

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -45,6 +45,17 @@ jobs:
             echo "CHANGELOG.md does not contain a section for $VERSION"
             exit 1
           fi
+      - name: Validate pub.dev topics
+        id: validate_pub_dev_topics
+        run: |
+          set -e
+          pattern="^[a-z][a-z0-9-]*[a-z0-9]$"
+          for topic in $(yq -r '.topics[]' pubspec.yaml); do
+            if [[ ! $topic =~ $pattern ]]; then
+              echo "Invalid topic: $topic"
+              exit 1
+            fi
+          done
       - name: Install dependencies
         run: dart pub get
       - name: Publish
